### PR TITLE
docs: add contributors section

### PR DESCRIPTION
**Pull request by Glorycs29**
docs: add contributors section

### CODE REVIEW

**Comment by hitesh22rana** [comment]
Hey @Glorycs29 , wonderful job
your commit message should be in this form :- <Type>: <subject> and everything should be in small letters
refer:- https://github.com/hitesh22rana/OptySys/blob/main/CONTRIBUTION.md
can you update it?

**Comment by Glorycs29** [comment]
okay I'll Update it

**Comment by hitesh22rana** [comment]
PR should be raised with this message :- docs: add contributors section

**Review by Glorycs29 — COMMENTED** [review]
docs: add contributors section

**Pull request merged**
