### PR TITLE
 signUp form

### LINKED ISSUE #18: [bug]: signup form
title: signup for is blank
image

### PR DESCRIPTION
**Pull request by sagar7170**
added signup form
Fixes #18

### CODE REVIEW

**Comment by hitesh22rana** [comment]
hey @sagar7170 , did you test the code?
also, PR message do not not follow the guidelines, could you resolve both of these issues.

also, if you are enable to test with backend, do use the api part, just make the frontend.

**Comment by sagar7170** [comment]
yeah I have tested the code by my side and it's working fine
and what PR  message guidelines? i did not get

**Comment by hitesh22rana** [comment]
> yeah I have tested the code by my side and it's working fine and what PR message guidelines? i did not get

@sagar7170  refer these guidelines:-
both the commit message an PR  should follow these guidelines, also the code won't work as it is calling the login api.

https://github.com/hitesh22rana/OptySys/blob/main/CONTRIBUTION.md
https://github.com/hitesh22rana/OptySys/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by hitesh22rana** [comment]
@sagar7170 you still working on this?

**Comment by sagar7170** [comment]
I'm not able  connect register api in the signup form

**Comment by hitesh22rana** [comment]
Alright @sagar7170 I’ll take the lead for now can you design the landing page of the web application using figma?

**Comment by sagar7170** [comment]
I don't know how to use figma , but i can try to code the design if you provide figma design

**Comment by hitesh22rana** [comment]
> I don't know how to use figma , but i can try to code the design if you provide figma design

I have the same issue that’s why j asked 😔

**Comment by sagar7170** [comment]
Btw how do you want the figma design

**Comment by hitesh22rana** [comment]
> Btw how do you want the figma design

don't have anything specific in mind simple and sober landing page maybe which tells about the product with some images.

**Comment by sagar7170** [comment]
I'm not getting the idea of design,
why you not directly start code the design

**Comment by hitesh22rana** [comment]
> I'm not getting the idea of design, why you not directly start code the design

alright i'll take the lead thanks mate

**Pull request closed without merging**
